import numpy

class PolygonSet:
    def __init__(self, connectivity: int) -> None: ...
    def num_objects(self) -> int: ...
    def add_tile(self, tile: numpy.ndarray, start: tuple[int, int, int], stop: tuple[int, int, int]) -> 'PolygonSet': ...
    def digest(self) -> 'PolygonSet': ...
    def extract_tile(self, tile: numpy.ndarray, start: tuple[int, int, int], stop: tuple[int, int, int]) -> 'PolygonSet': ...


def drop_polygon_set(polygon_set: PolygonSet) -> None: ...
